# Generated by Django 3.1 on 2021-12-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20211208_2338'),
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='product',
        ),
        migrations.AddField(
            model_name='factura',
            name='sale',
            field=models.ManyToManyField(default=None, to='sales.Venta'),
        ),
    ]
