# Generated by Django 3.1 on 2021-12-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20211208_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='RUC',
            field=models.CharField(default=None, max_length=12, verbose_name='RUC'),
        ),
        migrations.AddField(
            model_name='factura',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='factura',
            name='phone_number',
            field=models.CharField(default=None, max_length=9, verbose_name='Numero de telefono'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emision'),
        ),
    ]
