# Generated by Django 3.1 on 2021-11-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RUC', models.CharField(max_length=12, verbose_name='RUC')),
                ('DNI', models.CharField(max_length=8, verbose_name='DNI')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de cliente')),
                ('adress', models.CharField(max_length=50, verbose_name='Direccion')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('phone_number', models.CharField(max_length=9, verbose_name='Numero de telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('site_web', models.URLField(blank=True, verbose_name='Sitio web')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
