# Generated by Django 3.1 on 2021-11-11 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
        ('customers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('payment_status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VENCIDO', 'Vencido'), ('PAGADO', 'Pagado')], max_length=50, verbose_name='Estado de pago')),
                ('sale_status', models.CharField(choices=[('COMPLETADO', 'Completado'), ('PENDIENTE', 'Pendiente')], max_length=50, verbose_name='Estado de venta')),
                ('sale_date', models.DateTimeField(verbose_name='Fecha de venta')),
                ('customer', models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='customers.cliente', verbose_name='Cliente')),
                ('product', models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
