# Generated by Django 3.1 on 2021-12-02 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='sale_status',
        ),
    ]
