# Generated by Django 3.1 on 2021-12-02 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0003_auto_20211201_1912'),
        ('sales', '0002_remove_venta_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='customers.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.producto', verbose_name='Producto'),
        ),
    ]
