# Generated by Django 3.1 on 2021-12-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20211202_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='bill_status',
            field=models.CharField(choices=[('FACTURADO', 'Facturado'), ('NO FACTURADO', 'No Facturado')], default='NO FACTURADO', max_length=15, verbose_name='Estado de factura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='payment_status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VENCIDO', 'Vencido'), ('PAGADO', 'Pagado')], max_length=15, verbose_name='Estado de pago'),
        ),
    ]
