# Generated by Django 3.1 on 2021-12-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='description',
            field=models.TextField(default='Descripcion del producto', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del producto'),
        ),
    ]
