# Generated by Django 3.1 on 2021-12-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211201_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='description',
            field=models.TextField(max_length=100, verbose_name='Descripcion'),
        ),
    ]
